export const ADD_INGREDIENT = "ADD_INGREDIENT";

export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";

export const UPDATE_PURCHASABLE = "UPDATE_PURCHASABLE";

<<<<<<< HEAD
export const RESET_INGREDIENTS = "RESET_INGREDIENTS";


export const LOAD_ORDERS = "LOAD_ORDERS";

export const ORDER_LOAD_FAILED = "ORDER_LOAD_FAILED";
=======
export const RESET_INGREDIENTS = "RESET_INGREDIENTS";
>>>>>>> 6107ce04308d3b19588eefbb762dfaf57c1bf8ec
